### ISSUE TITLE
Potential use after free using ActorRequest

### ISSUE THREAD

**Issue by wiktorwieclaw** [drogue-iot/ector#11]
Here you are illegally transmuting a `DynamicSender<'a, ...>` to `DynamicSender<'static, ...>`.

https://github.com/drogue-iot/ector/blob/0505b2f4c2f91f7a7682e95a5c7f20b9c7d5ee2a/ector/src/actor.rs#L77-L89

You are not actually guaranteeing that the channel will outlive the sender. It's possible to call the `request` function with [`embassy_time::with_timeout`](https://docs.embassy.dev/embassy-time/git/default/fn.with_timeout.html) or [`embassy_futures::select`](https://docs.embassy.dev/embassy-futures/git/default/select/fn.select.html), which in turn could cancel the `recv`'s future and drop the channel before the sender is used, resulting in a dangling reference.

To illustrate, I edited the [examples/request.rs](https://github.com/drogue-iot/ector/blob/main/ector/examples/request.rs)
```rust
async fn test(addr: DynamicAddress<Request<&'static str, &'static str>>) {
    let _ = embassy_time::with_timeout(Duration::from_micros(1), addr.request("Hello")).await;
}
```
[full source code and miri output here](https://github.com/wiktorwieclaw/ector-ub)

`ActorRequest::request` is a safe API and it should be impossible to cause UB with it, either mark it as unsafe, or rework it. I'm not actually sure you can do this safely without declaring the channel as `static` or without dynamic allocation.

**Comment by lulf** [comment]
I agree this should be better documented, thanks for reporting the issue. Marking as unsafe sounds a bit too much, but maybe using #[must_use] to ensure the future is awaited.

**Comment by wiktorwieclaw** [comment]
> Marking as unsafe sounds a bit too much, but maybe using #[must_use] to ensure the future is awaited.

Sorry but I have to strongly disagree. ["No matter what, Safe Rust can't cause Undefined Behavior"](https://doc.rust-lang.org/nomicon/safe-unsafe-meaning.html#:~:text=No%20matter%20what%2C%20Safe%20Rust%20can%27t%20cause%20Undefined%20Behavior.). I'm not an expert, but I think that once you extend the lifetime to `static`, you have to somehow guarantee that the object will live until **the end of the program** and I don't think it can be done in this particular case (without alloc).

I've been trying to implement my own no-alloc actors framework and I really wanted to have a notion of oneshot channels that'd allow me to respond to messages, but I came to the conclusion that it just cannot be done in safe Rust without allocation and I decided to drop this idea.

I hope you can prove me wrong ;P

**Comment by lulf** [comment]
I'm certainly not an expert either, but I've seen exceptions to this rule in various embedded framework, for instance around DMA, because there might be some edge cases where you could cause undefined behavior, but you'd really have to go out of your way to achieve that.

In this case, if you could somewhat enforce that the request() future will await'ed, even if the lifetime of the channel is extended to static, you know that nothing will be referencing it because it cannot be leaked by the receiver (it's private inside the request). So once the notification arrives, you know that the other side will no longer reference the channel (because it's within the actor framework).

But last time i looked at must_use, it didn't properly enforce awaiting the future (https://github.com/rust-lang/rust/issues/78149). I thought there was some changes in this recently but haven't found it.

**Comment by xgroleau** [comment]
The issue in the end is async cancellation and there are no real way to prevent it since it can be cancelled from "up", thus even if we require this particular future to be awaited, the function that awaits the request can still be cancelled from where it's called.

Ex
```rs
async cancelled(addr: DynamicAddress<Request<&'static str, &'static str>>) -> &'static str {
  // Not cancelled here and awaited as requested by the #[must_use]
  addr.request("Hello").await
}

async fn test(addr: DynamicAddress<Request<&'static str, &'static str>>) {
    // Cancelled here
    let _ = embassy_time::with_timeout(Duration::from_micros(1),  cancelled(addr)).await;
}
```

We could instead let the user provide  a static `RequestState` which would hold the `Channel` to the function, now you would still received the message from the cancelled request, but that could maybe be managed internally by the `RequestState` via counting the uncompleted requests.  That would hurt the ease of use of the api so I would probably keep the current implementation and document the limitation.

In essence we would have
```rs
pub trait ActorRequest<M, R> {
    /// RequestState is created with a 'static channel inside
    async fn request(&self, message: M, state: &RequestState) -> R;
}
```

Or we could instead of implementing `ActorRequest` directly on `DynamicSender`, we could wrap it in a struct that would take the static `Channel`. Similar to the first solution but we keep the same api, but have a bit more complexity on the creation/init. A macro could probably be provided to ease this

That would look like:
```rs
// RequestWrapper is created with a 'static channel inside
impl<'a, M, R> ActorRequest<M, R> for RequestWrapper<'a, Request<M, R>> {
    async fn request(&self, message: M) -> R {
        self.ignore_previous_requests().await;
        let message = Request::new(message, self.reply_addr);
        self.notify(message).await;
        channel.recv().await
    }
}
```

If we do want to fix this, I personally prefer the second solution since we keep the same API and the trait doesn't change. Also I fell it's a bit strange to provide the state in the function argument of the trait, you can clearly see the implementation detail in the trait signature with the first solution.

**Comment by lulf** [comment]
@xgroleau Thanks for expanding on this and highlighting the cancellation issue. I prefer the second solution as well for the same reason.
