### ISSUE TITLE
Multiple messages types for a single actor

### ISSUE THREAD

**Issue by purplethunder** [drogue-iot/ector#6]
The ector implementation appears to impose a one-to-one mapping between an actor and a given message type.  The [actix handler trait](https://docs.rs/actix/latest/src/actix/handler.rs.html#16-29) for example is parameterized to allow a given actor to handle multiple message types.  Is the one-to-one mapping by design or could ector be extended to support a single actor handling multiple message types?

**Comment by lulf** [comment]
It is kind of 'by design'. The reason is that  in order to be no-alloc and no-std, it must know the size of all messages through the actor inbox at compile time, and for the mount future to have a known size at compile time. Having gone through various iterations on this, we settled on the current design as the 'minimum' in the core.

However, you can support multiple message types for an actor in two ways:

* Create an enum message type with all the expected messages for your actor
* Enable alloc and use Box<dyn YourMessageTrait> as the message type for the actor

I think both of these can be made more pleasant using macros, but I'm not sure whether it need/should be part of the core ector, but an additional crate that simplifies one or both of the above.

**Comment by purplethunder** [comment]
Thank you, I had considered the enum solution, but Box could work here too.  Appreciate the prompt reply!
